version: '3.5'

services:
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/data/postgres
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped

volumes:
    postgres_data: