# Generated by Django 3.0.7 on 2020-08-21 16:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
