# Generated by Django 3.0.7 on 2020-11-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_divisions', '0002_administrativedivision_geographic_area'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrative_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='administrative_divisions.AdministrativeDivision'),
        ),
    ]
