# Generated by Django 3.0.7 on 2020-09-18 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200821_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geographic_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
