# Generated by Django 3.0.7 on 2020-11-15 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedivision',
            name='geographic_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
