# Generated by Django 3.0.5 on 2020-06-27 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('resources', '0002_resourcesindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Enter an ISBN (9, 10, or 13) with optional hyphens.', max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
