# Generated by Django 3.0.5 on 2020-06-27 19:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200627_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
