# Generated by Django 3.0.7 on 2020-09-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAppSetting',
            new_name='ClientAppSettings',
        ),
    ]
