# Generated by Django 3.0.7 on 2020-10-11 08:01

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbandesignpattern',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
