# Generated by Django 3.0.5 on 2020-05-15 17:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('patterns', '0004_urbandesignpatternindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanDesignPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt', models.CharField(help_text='Alternative text for accessibility.', max_length=250)),
                ('design_pattern', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='patterns.UrbanDesignPattern')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_patterns', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
